### ISSUE TITLE
请问这个问题是怎么回事啊

### ISSUE THREAD

**Issue by happy20200** [Whu-wxy/DistNet#3]
![1666237965395](https://user-images.githubusercontent.com/59427046/196852473-3f3f55ca-205a-408b-9571-f536a99020fd.png)

**Comment by Whu-wxy** [comment]
环境还没有配置好：
需要编译opencv：Download and compile opencv(3.x) source code.
pck-config问题: apt-get install pck-config

不同版本python编译cpp遇到的问题可以查看https://github.com/Whu-wxy/DistNet/blob/master/dist/%E4%B8%8D%E5%90%8C%E7%89%88%E6%9C%ACpython%E7%BC%96%E8%AF%91pse

**Comment by Whu-wxy** [comment]
另外，推荐使用cp分支，准确率更高
https://github.com/Whu-wxy/DistNet/tree/cp

**Comment by happy20200** [comment]
> 环境还没有配置好： 需要编译opencv：Download and compile opencv(3.x) source code. pck-config问题: apt-get install pck-config
> 
> 不同版本python编译cpp遇到的问题可以查看https://github.com/Whu-wxy/DistNet/blob/master/dist/%E4%B8%8D%E5%90%8C%E7%89%88%E6%9C%ACpython%E7%BC%96%E8%AF%91pse

谢谢您的回复，不过我用的是windows，请问代码可以使用吗

**Comment by Whu-wxy** [comment]
不清楚，我从来没用过windows跑过这个代码

**Comment by happy20200** [comment]
> 不清楚，我从来没用过windows跑过这个代码

好的，我再配置一下环境
