### ISSUE TITLE
请问二值化是怎么处理的啊，固定阈值吗

### ISSUE THREAD

**Issue by happy20200** [Whu-wxy/DistNet#4]
您好，感谢您出色的工作，请问Binary Map中的阈值是怎么设置的啊，固定阈值吗

**Comment by happy20200** [comment]
另外，因为之前没怎么接触过深度图，所以想问一下，您文章里的深度图和近似二值图是怎么得到的，output block的输出就是这两项吗

**Comment by happy20200** [comment]
还想请问，深度图不是根据物体的远近的来的吗，这怎么能区别文本和背景啊，很多情况下背景和文本的深度不应该是一样的吗

**Comment by Whu-wxy** [comment]
1.Binary Map阈值是固定的
2.最终输出就是这两个图，深度图可以看生成label的代码，是从二值图做距离变换得到的
3.不是深度，是距离图，区域内部像素标记为与最近非文本像素的距离，详细看opencv距离变换算法

**Comment by happy20200** [comment]
好的，谢谢您的回复，我会根据您的回复仔细研究相关问题
